theme: jekyll-theme-midnight
name: The Blog
title: SM USAMA SHAH 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

gems:
  - [jekyll-mermaid]
  
mermaid:
  src: 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0/mermaid.js'

feature:
  disqus: true
  sharing: true

# Post sharing icons
sharing:
  twitter: true
  linkedin: true
  facebook: true
  google_plus: true
  reddit: true
  stumble: true

sass:
  style: compressed
  
# jekyl-seo-tag plugin
image: /image.png
