theme: jekyll-theme-midnight
name: The Blog
title: SM USAMA SHAH 
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

feature:
  disqus: true
  sharing: true

# Post sharing icons
sharing:
  twitter: true
  linkedin: true
  facebook: true
  google_plus: true
  reddit: true
  stumble: true

sass:
  style: compressed
  
# jekyl-seo-tag plugin
image: /image.png
