name: Deploy static site

on:
  workflow_dispatch:
  push:
    branches:
      - source

permissions:
  contents: write

concurrency:
  group: deploy-static-site
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish static files
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./
          exclude_assets: '.github,README.md'
