name: CI
on:
  workflow_dispatch:
    # inputs:
    #   dynalistFileId:
    #     description: "Dynalist file ID"
    #     required: false
    #   dynalistNodeId:
    #     description: "Dynalist node ID"
    #     required: false
  push:
    branches:
      - source  # default branch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
      # - name: Update theme
      #   run: git submodule update --init --recursive

      - name: Update articles from dynalist
        uses: ./action-dynalist
        with:
          DYNALIST_TOKEN: ${{ secrets.DYNALIST_TOKEN }}

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.REPO_ACCESS }}
          # external_repository: smusamashah/smusamashah.github.io
          publish_dir: ./public # this directory will be published on the pubish branch
          #   keep_files: true
          # user_name: SMUsamaShah
          # user_email: <lifeh2o@gmail.com>
          publish_branch: master
        #   cname: example.com
